### PR TITLE
Better link to Maven in the badge

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by armanbilge** [comment]
Thanks! But at least for me the link doesn't seem to point to the right place.

https://search.maven.org/search?q=g%3Aio.chrisdavenport+AND+a%3Ahttp4s-grpc-google-*

Maybe we should link to scaladex instead?
https://index.scala-lang.org/davenverse/googleapis-http4s

**Comment by sideeffffect** [comment]
The point is to link to a list of available artifacts.
index.scala-lang.org/davenverse/googleapis-http4s doesn't point to any and so you don't know what is available in what version
But it's OK if you prefer the current link, I'm not insisting ;)

**Comment by armanbilge** [comment]
Hmm, I wonder if we are not seeing the same thing 😕 

When I click on your link, I see this:

<details>

Screen Shot 2023-04-07 at 11 33 49 AM

</details>

Meanwhile at Scaladex, I see this.

<details>

Screen Shot 2023-04-07 at 11 34 18 AM

</details>

**Comment by sideeffffect** [comment]
You have the new Maven UI, which sucks :(
The old one looks like this

image

Scaladex might not be bad... I don't know :)

**Comment by sideeffffect** [comment]
So what do we do about this, @armanbilge ?

**Comment by armanbilge** [comment]
Can we find a URL that won't bitrot when Maven switches permanently to the new UI?

**Comment by sideeffffect** [comment]
I updated the link, please have a look

**Comment by armanbilge** [comment]
That link works on my end, thank you so much!

**Comment by sideeffffect** [comment]
Happy to help :bow:

**Pull request merged**
